from itertools import combinations, product

import pytest

from delta_matroid import DeltaMatroid, MatchingGraph, det_mod_p
from delta_matroid.exchange import BitmaskExchangeEngine
from verification.dmlib import (
    antipode_strong,
    binary_representable,
    det_mod,
    hyperplane_delta,
    hyperplane_even,
    is_delta,
    is_even_sys,
    lift,
    neighbors as oracle_neighbors,
    pm_family_dp,
    family_gf2,
    skew_family_modp,
    ternary_representable,
    turn1_weak_verifier,
    weak_wenzel,
    wenzel,
)


def all_families(n):
    subsets = tuple(range(1 << n))
    for code in range(1, 1 << len(subsets)):
        yield {subsets[i] for i in range(len(subsets)) if (code >> i) & 1}


def test_constructor_acceptance_matches_independent_delta_oracle_n3():
    n = 3
    for family in all_families(n):
        expected_delta = is_delta(family)
        if expected_delta:
            D = DeltaMatroid(range(n), (
                {i for i in range(n) if mask >> i & 1}
                for mask in family
            ))
            assert D.verify_delta_axiom() is None
            assert D.is_even() == is_even_sys(family)
            if D.is_even():
                assert D.verify_wenzel() is None
                assert wenzel(family)
        else:
            with pytest.raises(ValueError, match="symmetric exchange"):
                DeltaMatroid(range(n), (
                    {i for i in range(n) if mask >> i & 1}
                    for mask in family
                ))


def test_theorem_a_strong_delta_characterizations_match_on_all_n3_families():
    n = 3
    for family in all_families(n):
        if not is_delta(family):
            continue
        lifted = lift(family, n)
        strong = hyperplane_delta(family)
        assert weak_wenzel(family) is strong
        assert (is_delta(lifted) and is_even_sys(lifted)) == strong
        assert antipode_strong(family) is strong


def test_theorem_a_strong_delta_characterizations_match_on_all_n4_families():
    n = 4
    checked = 0
    for family in all_families(n):
        if not is_delta(family):
            continue
        checked += 1
        lifted = lift(family, n)
        strong = hyperplane_delta(family)
        assert weak_wenzel(family) is strong
        assert (is_delta(lifted) and is_even_sys(lifted)) == strong
        assert antipode_strong(family) is strong
    assert checked == 5959


def test_theorem_2_3_even_characterizations_match_on_all_even_n3_delta_families():
    n = 3
    for family in all_families(n):
        if not (is_delta(family) and is_even_sys(family)):
            continue
        assert hyperplane_even(family)
        assert wenzel(family)


def test_theorem_2_3_even_characterizations_match_on_all_even_n4_delta_families():
    n = 4
    checked = 0
    for family in all_families(n):
        if not (is_delta(family) and is_even_sys(family)):
            continue
        checked += 1
        assert hyperplane_even(family)
        assert wenzel(family)
    assert checked == 294


def test_historical_unordered_weak_verifier_has_known_n3_false_positive():
    family = {1, 2, 3, 4}
    assert turn1_weak_verifier(family)
    assert not is_delta(family)


def test_lazy_exchange_neighbors_match_independent_oracle():
    G = MatchingGraph.from_edges(
        range(7),
        [(0, 1), (0, 2), (1, 3), (2, 3), (2, 4), (4, 5), (5, 6), (3, 6)],
    )
    D = G.delta_matroid()
    masks = bytearray(1 << 7)
    for F in D.feasible_sets:
        masks[D.mask(F)] = 1

    engine = BitmaskExchangeEngine(7, masks, even=True)
    oracle_family = masks_to_family(masks)
    for X in range(1 << 7):
        if not masks[X]:
            continue
        expected = set(oracle_neighbors(oracle_family, X, 7, mode="both"))
        assert set(engine.neighbors(X)) == expected


def masks_to_family(masks):
    return {mask for mask, ok in enumerate(masks) if ok}


def test_matching_subset_dp_matches_independent_oracle_on_all_graphs_n5():
    n = 5
    pairs = list(combinations(range(n), 2))
    for code in range(1 << len(pairs)):
        edges = [pairs[i] for i in range(len(pairs)) if (code >> i) & 1]
        G = MatchingGraph.from_edges(range(n), edges)
        actual = G.feasible_masks()

        adj = [0] * n
        for u, v in edges:
            adj[u] |= 1 << v
            adj[v] |= 1 << u

        expected = pm_family_dp(n, adj)
        assert actual == expected


def test_modular_determinant_matches_independent_oracle():
    matrices = (
        ((1, 2), (3, 4)),
        ((0, 1, 2), (3, 4, 5), (6, 7, 8)),
        ((5, -2, 7, 11), (3, 4, -9, 2), (8, 1, 6, -4), (0, 3, 5, 7)),
    )
    p = 101
    for matrix in matrices:
        assert det_mod(matrix, p) == det_mod_p(matrix, p)


def test_ternary_cap_does_not_abort_later_decidable_twist():
    # G is generated by a GF(3) skew matrix supported on a tree.
    matrix = [[0] * 5 for _ in range(5)]
    for i, j in ((0, 2), (1, 2), (2, 4), (3, 4)):
        matrix[i][j] = 1
        matrix[j][i] = 2
    G = [20, 0, 5, 6, 24, 29, 30]
    assert skew_family_modp(matrix, 5, 3) == set(G)

    # The first feasible X=20 creates a twist whose support has two
    # non-tree edges, so cap=1 forces that candidate to be skipped.
    # The later feasible X=0 is directly representable and must still be tried.
    from verification.dmlib import ternary_representable
    assert ternary_representable(G, 5, p=3, cap=1) is True


def _even_uniform_families(n):
    subsets = tuple(range(1 << n))
    even_masks = tuple(s for s in subsets if s.bit_count() % 2 == 0)
    odd_masks = tuple(s for s in subsets if s.bit_count() % 2 == 1)
    for source in (even_masks, odd_masks):
        for code in range(1, 1 << len(source)):
            yield frozenset(source[i] for i in range(len(source)) if code >> i & 1)


def _all_gf2_symmetric_families(n):
    positions = [(i, j) for i in range(n) for j in range(i, n)]
    out = set()
    for bits_value in range(1 << len(positions)):
        rows = [0] * n
        for k, (i, j) in enumerate(positions):
            if (bits_value >> k) & 1:
                rows[i] |= 1 << j
                if i != j:
                    rows[j] |= 1 << i
        out.add(frozenset(family_gf2(rows, n)))
    return out


def _all_gf3_skew_families(n):
    positions = [(i, j) for i in range(n) for j in range(i + 1, n)]
    out = set()
    for values in product((0, 1, 2), repeat=len(positions)):
        matrix = [[0] * n for _ in range(n)]
        for (i, j), value in zip(positions, values):
            matrix[i][j] = value
            matrix[j][i] = (-value) % 3
        out.add(frozenset(skew_family_modp(matrix, n, 3)))
    return out


def _all_twists(families, n):
    return {
        frozenset(S ^ X for S in family)
        for family in families
        for X in range(1 << n)
    }


def test_binary_representability_matches_exhaustive_gf2_matrices_for_all_n4_even_families():
    n = 4
    represented = _all_twists(_all_gf2_symmetric_families(n), n)
    for family in _even_uniform_families(n):
        assert binary_representable(set(family), n) is (family in represented)


def test_ternary_representability_matches_exhaustive_gf3_skew_matrices_for_all_n4_parity_uniform_families():
    n = 4
    represented = _all_twists(_all_gf3_skew_families(n), n)
    for family in _even_uniform_families(n):
        assert ternary_representable(set(family), n, p=3) is (family in represented)


def test_isolated_antipode_requires_exactly_two_feasible_sets_in_the_interval():
    from verification.dmlib import has_isolated_antipode, theorem_a_local_antipode_condition

    # In the 5-cube, opposite vertices are isolated only when no third
    # feasible set lies anywhere in their interval.
    assert has_isolated_antipode({0, 31}, min_dimension=5)
    assert not theorem_a_local_antipode_condition({0, 31})

    # A third feasible set breaks isolation in that same interval.
    assert not has_isolated_antipode({0, 31, 1}, min_dimension=5)

    # The complete cube has no isolated antipodes and no peerless 3-/4-cube.
    full_cube = set(range(32))
    assert not has_isolated_antipode(full_cube, min_dimension=5)
    assert theorem_a_local_antipode_condition(full_cube)


def test_theorem_a_fifth_characterization_matches_strong_status_for_all_n4_delta_matroids():
    from verification.dmlib import theorem_a_local_antipode_condition

    n = 4
    checked = 0
    for family in all_families(n):
        if not is_delta(family):
            continue
        checked += 1
        assert theorem_a_local_antipode_condition(family) is hyperplane_delta(family)
    assert checked == 5959
